### ISSUE TITLE
What is the normalization for the FFT operations?

### ISSUE THREAD

**Issue by nkarve** [aromanro/DFTQuantumDot#5]
How are the FFT and inverse FFT operations normalized during the cI/cIdag and cJ/cJdag routines? 

I know FFTW uses unnormalised transforms, but I don't think that works. My guess is that they are symmetrically normalized (i.e. with a 1/sqrt(N) factor both forward and backward) so that the following two conditions are preserved (assuming square matrices for now):

- cI(cIdag(X)) = X
- (a† I b)* = (b† I† a)

So is the normalization symmetric? If so, do you include the number of orbitals in the normalization factor? If not, are either of these assumptions wrong?

**Comment by aromanro** [comment]
That's a good question, it's been a while since I implemented this.
Usually, normalization isn't needed, or it's done explicitly, but from a brief look over the code to refresh my memory about it, I cannot tell with certainty what's going on with cI and cIdag.

I'll look more into it.

If it helps you, I also implemented almost the same thing here in python: https://github.com/aromanro/PythonCompphys (the dft notebook). Also, the lectures and the assignments might be of help.

**Comment by aromanro** [comment]
From more looking over the code, it appears that the math checks out.
cJ is actually the cI^-1.

You'll notice 
`const double norm = 1. / realSpaceCell.Samples();`
in cJ and cJdag, that takes care of it.

Where you simply see only cI and cIdag, it turns out that the avoidance of normalization is intentional.
